name: lsp-playground
version: 0.1.0
license: BSD3
author: "Jan Mas Rovira"
maintainer: "janmasrovira@gmail.com"
description: "LSP practice"
category: Development

extra-source-files: []

dependencies:
  - array == 0.5.*
  - base >= 4.7 && < 5
  - bytestring == 0.12.*
  - containers == 0.6.*
  - deepseq == 1.5.*
  - effectful == 2.3.*
  - effectful-core == 2.3.*
  - effectful-th == 1.0.*
  - exceptions == 0.10.*
  - extra == 1.7.*
  - filepath == 1.4.*
  - hashable == 1.4.*
  - lens == 5.2.*
  - lsp == 2.6.*
  - lsp-types == 2.2.*
  - megaparsec == 9.*
  - parser-combinators == 1.3.*
  - path == 0.9.*
  - path-io == 1.8.*
  - pretty == 1.1.*
  - prettyprinter == 1.7.*
  - prettyprinter-ansi-terminal == 1.1.*
  - safe == 0.3.*
  - Stream == 0.4.*
  - template-haskell == 2.21.*
  - text == 2.1.*
  - unordered-containers == 0.2.*

ghc-options:
  # Warnings
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-missing-role-annotations
  - -Wno-missing-poly-kind-signatures
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-unused-packages
  # HIE Support
  - -fhide-source-paths
  - -fwrite-ide-info -hiedir=.hie
  # Optimization
  - -O2

default-extensions:
  - ApplicativeDo
  - DataKinds
  - DerivingStrategies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NoFieldSelectors
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilyDependencies

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  minilang-lsp:
    main: Main.hs
    source-dirs: app
    dependencies:
      - lsp-playground
    verbatim:
      default-language: GHC2021
